language: node_js
node_js:
  - "8"
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c 'CREATE TABLE public.entries(id serial primary key, title character varying(200) NOT NULL, details character varying(10000) NOT NULL, last_time_edited date NOT NULL DEFAULT CURRENT_DATE)' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_success:
  - npm run coverage
  - cd my-Diary ./cc-test-reporter after-build -d --exit-code $TRAVIS_TEST_RESULT -t lcov