language: node_js
node_js:
  - "8"
services:
  - postgresql
addons:
  postgresql: "10.4"
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database test_db;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_success:
  - npm run coverage
  - cd my-Diary ./cc-test-reporter after-build -d --exit-code $TRAVIS_TEST_RESULT -t lcov