language: node_js
node_js:
  - "stable"
services:
  - postgresql
addons:
  postgresql: "10.4"
before_script:
  - psql -c 'create database db_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_success:
  - npm run coverage
  - ./cc-test-reporter after-build -d --exit-code $TRAVIS_TEST_RESULT