language: node_js
node_js:
  - "8"
services:
  - postgresql
before_script:
  - psql -c 'create database MyDiary;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - cd my-Diary ./cc-test-reporter after-build -d --exit-code $TRAVIS_TEST_RESULT
after_success:
  - npm run coverage